# api_key: 'key-cf8506cf27334e76d6188d3dcd52064a'
# domain: 'sandboxab68412aee7e40d88ad93dc17abc623e.mailgun.org'
# username: 'postmaster@sandboxab68412aee7e40d88ad93dc17abc623e.mailgun.org'
# password: '738f1f374f0309bbd6234e00cf38ce2d'
# gmail_username: 'stockpricetracker@gmail.com'
# gmail_password: 'Blackstar1234'